### PR TITLE
Unbitrot this project so I can use it again as a starter.

### LINKED ISSUE #1: Gulp dies a painful death when trynig to build this thing.
I tried to run this today, and to my dismay it doesn't work anymore. Well, that's a surprise, isn't it?

### PR DESCRIPTION
**Pull request by Idorobots**
Fixes #1 #2

### CODE REVIEW

File: frontend/gulpfile.js [hunk 1]
```diff
@@ -17,20 +17,63 @@ const uglify = require("gulp-uglify");
 const postcss = [ // order matters
   require("postcss-cssnext"),
   require("postcss-custom-properties"),
-  require("postcss-import"),
+  //require("postcss-import"), // FIXME
```
Comment (Idorobots) [inline frontend/gulpfile.js:20]: Yeah, I suppose this isn't needed anymore.
